### PR TITLE
IPv6 commit part 2

### PR DESCRIPTION
**Pull request by minhnguyenhoang**
Disabling IPv6 code committed

### CODE REVIEW

**Review by AnzoDK — CHANGES_REQUESTED** [review]
I would be preferable to let the user know before hand that IPv6 would be disabled, as some users really depend on it. Asking the user would be a much better idea and *then* disabling it if they approve

**Comment by AnzoDK** [comment]
> I would be preferable to let the user know before hand that IPv6 would be disabled, as some users really depend on it. Asking the user would be a much better idea and _then_ disabling it if they approve

actually it would be better to check if it is enabled in the first place, so that we can automatically enable it again when we are done, lightening the burden on the end user

**Comment by minhnguyenhoang** [comment]
sysctl = 1 automatically disables it. And yes, maybe prompting to disable IPv6 is a good idea

**Comment by minhnguyenhoang** [comment]
aaa how do i see requested changes lmfao

**Comment by minhnguyenhoang** [comment]
aight closing, new pull soon

**Pull request closed without merging**
